[MFLOG|0|2024-12-14T18:47:49.361391Z|runtime|aec5d70b-0a47-43c6-b5e2-b37056e01d3e]2024-12-14 19:47:49,360 [WARNING] Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x17aa30d10>, 'Connection to 18.208.160.74 timed out. (connect timeout=120)')': /api/2.0/mlflow/runs/get?run_uuid=86f31ebd2b654dd490c6117690907b41&run_id=86f31ebd2b654dd490c6117690907b41
[MFLOG|0|2024-12-14T18:48:10.997979Z|runtime|0a9ec636-d3a1-4b5e-acd8-c7cc8404022b]2024-12-14 19:48:10,997 [WARNING] Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x17b0cdf10>, 'Connection to 18.208.160.74 timed out. (connect timeout=120)')': /api/2.0/mlflow/runs/get?run_uuid=86f31ebd2b654dd490c6117690907b41&run_id=86f31ebd2b654dd490c6117690907b41
[MFLOG|0|2024-12-14T18:48:36.660282Z|runtime|3400372d-8d37-45d4-a1cf-55301130777d]2024-12-14 19:48:36,659 [WARNING] Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x17b0cc770>, 'Connection to 18.208.160.74 timed out. (connect timeout=120)')': /api/2.0/mlflow/runs/get?run_uuid=86f31ebd2b654dd490c6117690907b41&run_id=86f31ebd2b654dd490c6117690907b41
[MFLOG|0|2024-12-14T18:49:10.317257Z|runtime|6b7f83c5-908d-4b14-bcba-716206a1e1b4]2024-12-14 19:49:10,316 [WARNING] Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x17b0cff50>, 'Connection to 18.208.160.74 timed out. (connect timeout=120)')': /api/2.0/mlflow/runs/get?run_uuid=86f31ebd2b654dd490c6117690907b41&run_id=86f31ebd2b654dd490c6117690907b41
[MFLOG|0|2024-12-14T18:50:57.497401Z|runtime|8f6de5ba-b215-40bc-9e79-b68c423a6938]2024-12-14 19:50:57,496 [WARNING] Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x17b0cd400>, 'Connection to 18.208.160.74 timed out. (connect timeout=120)')': /api/2.0/mlflow/runs/get?run_uuid=86f31ebd2b654dd490c6117690907b41&run_id=86f31ebd2b654dd490c6117690907b41
